version: "3.7"
services:
  app:
    build:
      args:
        user: ksn38
        uid: 1000
      context: ./backend/laravel
      dockerfile: Dockerfile
    image: ms4
    container_name: ms4-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend/laravel:/var/www
    networks:
      - ms4-network
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0

  db:
    image: postgres:12
    container_name: ms4-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: djdb
      POSTGRES_USER: ksn38
      POSTGRES_PASSWORD: 1
    volumes:
      - ./backend/psql:/var/lib/postgresql/data
      - ./backend/psql_dump:/home/ksn38
    networks:
      - ms4-network
    ports:
      - "5432:5432"
    depends_on:
      - app

  nginx:
    depends_on:
      - app
      - node
    image: nginx:alpine
    container_name: ms4-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      # - ./backend/laravel:/var/www
      - ./backend/nginx/conf.d:/etc/nginx/conf.d/
      - ./backend/nginx/log:/var/log/nginx/
    networks:
      - ms4-network

  # sqla:
  #   build:
  #     args:
  #       user: ksn38
  #       uid: 1000
  #     context: ./backend/sqlalchemy/
  #   image: sqla
  #   container_name: ms4-sqla
  #   #restart: unless-stopped
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./backend/sqlalchemy/:/usr/src/app
  #   networks:
  #     - ms4-network

  node:
    build:
      args:
        user: ksn38
        uid: 1000
      context: ./frontend/node/
    image: "node14"
    container_name: ms4-node
    working_dir: /home/node/vue
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/node/:/home/node/
    ports:
      - "8081:8080"
    #stdin_open: true
    tty: true
    networks:
      - ms4-network
    command: npm run serve --host=0.0.0.0

networks:
  ms4-network:
    driver: bridge
