version: "3.7"
services:
  app:
    build:
      args:
        user: ksn38
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ms4
    container_name: ms4-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ms4-network

  db:
    image: postgres:12
    container_name: ms4-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: djdb
      POSTGRES_USER: ksn38
      POSTGRES_PASSWORD: 1
    volumes:
      - ./docker-compose/psql:/var/lib/postgresql/data
    networks:
      - ms4-network
    ports:
      - "5432:5432"
    depends_on:
      - app

  nginx:
    image: nginx:alpine
    container_name: ms4-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - ms4-network

  sqla:
    build:
      args:
        user: ksn38
        uid: 1000
      context: ./docker-compose/sqlalchemy/
    image: sqla
    container_name: ms4-sqla
    restart: unless-stopped
    volumes:
      - ./docker-compose/sqlalchemy/:/usr/src/app
    networks:
      - ms4-network

networks:
  ms4-network:
    driver: bridge
